import { User, AuditLog } from '../types';

export const MINISTERES = [
  'Ministère de l\'Intérieur',
  'Ministère de la Justice',
  'Ministère de l\'Éducation Nationale',
  'Ministère de la Santé Publique',
  'Ministère de l\'Agriculture',
  'Ministère des Finances',
  'Ministère du Commerce',
  'Ministère des Travaux Publics',
  'Ministère de la Culture',
  'Ministère de la Défense',
];

export const DEPARTEMENTS = [
  'Ouest',
  'Sud',
  'Nord',
  'Artibonite',
  'Centre',
  'Grand\'Anse',
  'Nippes',
  'Nord-Est',
  'Nord-Ouest',
  'Sud-Est',
];

export const defaultAdmin: User = {
  id: 'admin-001',
  fullName: 'Administrateur Principal',
  username: 'admin',
  email: 'admin@gov.ht',
  password: 'Admin2024!',
  role: 'ADMIN',
  status: 'ACTIVE',
  createdAt: new Date('2024-01-01').toISOString(),
  createdBy: 'SYSTEM',
};

export const mockUsers: User[] = [
  defaultAdmin,
  {
    id: 'user-002',
    fullName: 'Marie Claire Dubois',
    username: 'mdubois',
    email: 'marie.dubois@gov.ht',
    password: 'Password123!',
    role: 'RH',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-02-15').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-003',
    fullName: 'Jean Baptiste Pierre',
    username: 'jpierre',
    email: 'jean.pierre@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-03-10').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-004',
    fullName: 'Sophie Laurent',
    username: 'slaurent',
    email: 'sophie.laurent@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Nord',
    status: 'ACTIVE',
    createdAt: new Date('2024-03-20').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-005',
    fullName: 'Pierre Michel Joseph',
    username: 'pjoseph',
    email: 'pierre.joseph@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère de la Justice',
    departement: 'Sud',
    status: 'ACTIVE',
    createdAt: new Date('2024-04-05').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-006',
    fullName: 'Anne Marie François',
    username: 'afrancois',
    email: 'anne.francois@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Artibonite',
    status: 'ACTIVE',
    createdAt: new Date('2024-04-12').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-007',
    fullName: 'Jacques René Charles',
    username: 'jcharles',
    email: 'jacques.charles@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Centre',
    status: 'INACTIVE',
    createdAt: new Date('2024-05-01').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-008',
    fullName: 'Claudine Sylvain',
    username: 'csylvain',
    email: 'claudine.sylvain@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère de l\'Éducation Nationale',
    departement: 'Grand\'Anse',
    status: 'ACTIVE',
    createdAt: new Date('2024-05-15').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-009',
    fullName: 'Robert Antoine',
    username: 'rantoine',
    email: 'robert.antoine@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Nippes',
    status: 'ACTIVE',
    createdAt: new Date('2024-06-01').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-010',
    fullName: 'Madeleine Augustin',
    username: 'maugustin',
    email: 'madeleine.augustin@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Nord-Est',
    status: 'ACTIVE',
    createdAt: new Date('2024-06-10').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-011',
    fullName: 'Louis Philogène',
    username: 'lphilogene',
    email: 'louis.philogene@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère de la Santé Publique',
    departement: 'Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-07-01').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-012',
    fullName: 'Carole Désir',
    username: 'cdesir',
    email: 'carole.desir@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Nord-Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-07-15').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-013',
    fullName: 'Daniel Beauvoir',
    username: 'dbeauvoir',
    email: 'daniel.beauvoir@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Sud-Est',
    status: 'ACTIVE',
    createdAt: new Date('2024-08-01').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-014',
    fullName: 'Yvonne Laguerre',
    username: 'ylaguerre',
    email: 'yvonne.laguerre@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère de l\'Agriculture',
    departement: 'Artibonite',
    status: 'ACTIVE',
    createdAt: new Date('2024-08-10').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-015',
    fullName: 'Emmanuel Casimir',
    username: 'ecasimir',
    email: 'emmanuel.casimir@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Centre',
    status: 'INACTIVE',
    createdAt: new Date('2024-09-01').toISOString(),
    createdBy: 'mdubois',
  },
  {
    id: 'user-016',
    fullName: 'Lucienne Germain',
    username: 'lgermain',
    email: 'lucienne.germain@gov.ht',
    password: 'Password123!',
    role: 'RH',
    ministere: 'Ministère de la Santé Publique',
    departement: 'Sud',
    status: 'ACTIVE',
    createdAt: new Date('2024-09-15').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-017',
    fullName: 'Georges Étienne',
    username: 'getienne',
    email: 'georges.etienne@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère des Finances',
    departement: 'Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-09-20').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-018',
    fullName: 'Micheline Toussaint',
    username: 'mtoussaint',
    email: 'micheline.toussaint@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de la Santé Publique',
    departement: 'Nord',
    status: 'ACTIVE',
    createdAt: new Date('2024-09-25').toISOString(),
    createdBy: 'lgermain',
  },
  {
    id: 'user-019',
    fullName: 'André Dorsainvil',
    username: 'adorsainvil',
    email: 'andre.dorsainvil@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de la Santé Publique',
    departement: 'Grand\'Anse',
    status: 'ACTIVE',
    createdAt: new Date('2024-10-01').toISOString(),
    createdBy: 'lgermain',
  },
  {
    id: 'user-020',
    fullName: 'Martine Valcin',
    username: 'mvalcin',
    email: 'martine.valcin@gov.ht',
    password: 'Password123!',
    role: 'GRAND_COMMIS',
    ministere: 'Ministère du Commerce',
    departement: 'Ouest',
    status: 'ACTIVE',
    createdAt: new Date('2024-10-10').toISOString(),
    createdBy: 'admin',
  },
  {
    id: 'user-021',
    fullName: 'François Narcisse',
    username: 'fnarcisse',
    email: 'francois.narcisse@gov.ht',
    password: 'Password123!',
    role: 'FONCTIONNAIRE',
    ministere: 'Ministère de l\'Intérieur',
    departement: 'Nippes',
    status: 'ACTIVE',
    createdAt: new Date('2024-10-15').toISOString(),
    createdBy: 'mdubois',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    timestamp: new Date('2024-10-15T10:30:00').toISOString(),
    action: 'CREATE',
    performedBy: 'admin',
    performedByRole: 'ADMIN',
    targetUser: 'François Narcisse',
    targetUserId: 'user-021',
    details: 'Création d\'un nouveau fonctionnaire',
    ipAddress: '192.168.1.1',
  },
  {
    id: 'audit-002',
    timestamp: new Date('2024-10-14T14:20:00').toISOString(),
    action: 'UPDATE',
    performedBy: 'admin',
    performedByRole: 'ADMIN',
    targetUser: 'Jacques René Charles',
    targetUserId: 'user-007',
    details: 'Modification des informations utilisateur',
    changes: {
      departement: { old: 'Ouest', new: 'Centre' },
    },
    ipAddress: '192.168.1.1',
  },
  {
    id: 'audit-003',
    timestamp: new Date('2024-10-13T09:15:00').toISOString(),
    action: 'DEACTIVATE',
    performedBy: 'admin',
    performedByRole: 'ADMIN',
    targetUser: 'Emmanuel Casimir',
    targetUserId: 'user-015',
    details: 'Désactivation du compte utilisateur',
    ipAddress: '192.168.1.1',
  },
  {
    id: 'audit-004',
    timestamp: new Date('2024-10-12T16:45:00').toISOString(),
    action: 'ASSIGN',
    performedBy: 'admin',
    performedByRole: 'ADMIN',
    targetUser: 'Georges Étienne',
    targetUserId: 'user-017',
    details: 'Assignation au Ministère des Finances',
    changes: {
      ministere: { old: null, new: 'Ministère des Finances' },
    },
    ipAddress: '192.168.1.1',
  },
  {
    id: 'audit-005',
    timestamp: new Date('2024-10-11T11:00:00').toISOString(),
    action: 'CREATE',
    performedBy: 'mdubois',
    performedByRole: 'RH',
    targetUser: 'Micheline Toussaint',
    targetUserId: 'user-018',
    details: 'Création d\'un nouveau fonctionnaire',
    ipAddress: '192.168.1.5',
  },
];